#!/usr/bin/env node
/**
 * Generate the SQL that seeds monday_mirror.automations from an automation
 * inventory snapshot (the output of automations-from-mcp-dump.mjs).
 *
 *   node scripts/supabase-mirror/gen-seed.mjs supabase/snapshots/profile_send_off_automations.json \
 *     > services/supabase-mirror/db/0003_profile_send_off_automations.sql
 *
 * Idempotent (INSERT … ON CONFLICT DO UPDATE on the inventory columns), and it
 * never touches port_status / port_target / port_notes — those are the
 * working columns of the port and belong to whoever is doing it.
 */
import { readFileSync } from "node:fs";

const q = (v) => (v == null ? "NULL" : `'${String(v).replace(/'/g, "''")}'`);
const j = (v) => (v == null ? "NULL" : `${q(JSON.stringify(v))}::jsonb`);
const ts = (v) => (v ? `${q(v)}::timestamptz` : "NULL");

export function seedSql(inv) {
  const rows = [];
  for (const w of inv.workflows) {
    const title = [w.trigger?.block, ...w.conditions.map((c) => c.block), ...w.actions.map((a) => a.block)].filter(Boolean).join(" → ");
    rows.push(
      `(${inv.board_id}, ${w.id}, 'workflow', ${w.active ? "true" : "false"}, ${q(w.description || title)}, NULL, ${j(w.trigger)}, ${j(w.conditions)}, ${j(w.actions)}, NULL, ${ts(w.created_at)}, ${ts(w.updated_at)}, ${q(inv.snapshot_taken)}::date)`,
    );
  }
  for (const l of inv.legacy) {
    rows.push(
      `(${inv.board_id}, ${l.id}, 'legacy_recipe', ${l.active ? "true" : "false"}, ${q(l.sentence)}, ${q(l.sentence)}, NULL, NULL, NULL, ${j(l.config)}, ${ts(l.created_at)}, ${ts(l.updated_at)}, ${q(inv.snapshot_taken)}::date)`,
    );
  }
  return `-- GENERATED by scripts/supabase-mirror/gen-seed.mjs from an automation inventory
-- snapshot taken ${inv.snapshot_taken} (board ${inv.board_id}): ${inv.workflows.length} workflows,
-- ${inv.legacy.length} recipe automations. Do not edit by hand. Re-run after re-inventorying the board.
--
-- Board automations are not in monday's public API; the snapshot comes from the
-- monday MCP server's list_automations tool (see automations-from-mcp-dump.mjs).

INSERT INTO monday_mirror.automations
  (board_id, automation_id, kind, active, title, sentence, trigger, conditions, actions, config, monday_created_at, monday_updated_at, snapshot_taken)
VALUES
${rows.join(",\n")}
ON CONFLICT (board_id, automation_id) DO UPDATE SET
  kind = EXCLUDED.kind, active = EXCLUDED.active, title = EXCLUDED.title, sentence = EXCLUDED.sentence,
  trigger = EXCLUDED.trigger, conditions = EXCLUDED.conditions, actions = EXCLUDED.actions, config = EXCLUDED.config,
  monday_created_at = EXCLUDED.monday_created_at, monday_updated_at = EXCLUDED.monday_updated_at,
  snapshot_taken = EXCLUDED.snapshot_taken;
`;
}

const isMain = process.argv[1] && import.meta.url === new URL(`file://${process.argv[1]}`).href;
if (isMain) {
  const file = process.argv[2];
  if (!file) {
    console.error("usage: gen-seed.mjs <automations snapshot json>");
    process.exit(2);
  }
  process.stdout.write(seedSql(JSON.parse(readFileSync(file, "utf8"))));
}
