-- GENERATED by scripts/supabase-mirror/gen-view.mjs from Profile Send Off Board (board 18406352652),
-- shape snapshot 2026-09-29, 163 board columns. Do not edit by hand.
--
-- One row per mirrored item, one Postgres column per board column, typed.
-- Reads monday_mirror.items; nothing here is written by anyone.

DROP VIEW IF EXISTS monday_mirror.profile_send_off;
CREATE VIEW monday_mirror.profile_send_off AS
SELECT
  i.item_id,
  i.board_id,
  i.name,
  i.group_id,
  g.title AS group_title,
  i.state,
  i.monday_created_at,
  i.monday_updated_at,
  i.last_seen_at,
  i.missing_since,
  monday_mirror.cv_text(i.column_values, 'color_mm1zmeb3') AS move_to_onboarding, -- color_mm1zmeb3 · Move to Onboarding
  monday_mirror.cv_status_id(i.column_values, 'color_mm1zmeb3') AS move_to_onboarding_id, -- color_mm1zmeb3 · Move to Onboarding (label id)
  monday_mirror.cv_text(i.column_values, 'color_mm1xg10n') AS primary_insurance, -- color_mm1xg10n · Primary Insurance
  monday_mirror.cv_status_id(i.column_values, 'color_mm1xg10n') AS primary_insurance_id, -- color_mm1xg10n · Primary Insurance (label id)
  monday_mirror.cv_text(i.column_values, 'color_mm24ap4j') AS general_insurance, -- color_mm24ap4j · General Insurance
  monday_mirror.cv_status_id(i.column_values, 'color_mm24ap4j') AS general_insurance_id, -- color_mm24ap4j · General Insurance (label id)
  monday_mirror.cv_text(i.column_values, 'text_mm4t8gbq') AS member_id_working, -- text_mm4t8gbq · Member ID (text)
  monday_mirror.cv_text(i.column_values, 'text_mm1x2qk2') AS member_id1, -- text_mm1x2qk2 · Member ID 1 (text)
  monday_mirror.cv_text(i.column_values, 'color_mm1zbrx0') AS secondary_insurance, -- color_mm1zbrx0 · Secondary Insurance
  monday_mirror.cv_status_id(i.column_values, 'color_mm1zbrx0') AS secondary_insurance_id, -- color_mm1zbrx0 · Secondary Insurance (label id)
  monday_mirror.cv_text(i.column_values, 'text_mm1xaccx') AS member_id2, -- text_mm1xaccx · Member ID 2 (text)
  monday_mirror.cv_text(i.column_values, 'text_mm1xdcet') AS stedi_plan_name, -- text_mm1xdcet · Stedi Plan Name (text)
  monday_mirror.cv_text(i.column_values, 'dropdown_mm457xy2') AS stedi_home_plan, -- dropdown_mm457xy2 · Stedi Home Plan
  monday_mirror.cv_dropdown_ids(i.column_values, 'dropdown_mm457xy2') AS stedi_home_plan_ids, -- dropdown_mm457xy2 · Stedi Home Plan (label ids)
  monday_mirror.cv_text(i.column_values, 'dropdown_mm1y2x75') AS insurance_plan, -- dropdown_mm1y2x75 · Insurance Plan
  monday_mirror.cv_dropdown_ids(i.column_values, 'dropdown_mm1y2x75') AS insurance_plan_ids, -- dropdown_mm1y2x75 · Insurance Plan (label ids)
  monday_mirror.cv_text(i.column_values, 'text_mm25bjz7') AS stedi_secondary_medicaid_id, -- text_mm25bjz7 · Stedi Secondary / Medicaid ID (text)
  monday_mirror.cv_text(i.column_values, 'color_mm1yeksx') AS run_stedi_eligibility, -- color_mm1yeksx · Run Stedi Eligibility
  monday_mirror.cv_status_id(i.column_values, 'color_mm1yeksx') AS run_stedi_eligibility_id, -- color_mm1yeksx · Run Stedi Eligibility (label id)
  monday_mirror.cv_date(i.column_values, 'date_mm1wf43j') AS date_of_intake, -- date_mm1wf43j · Date of Intake
  monday_mirror.cv_time(i.column_values, 'date_mm1wf43j') AS date_of_intake_time, -- date_mm1wf43j · Date of Intake (time of day, ET)
  monday_mirror.cv_text(i.column_values, 'color_mm1wrrqz') AS referral_details, -- color_mm1wrrqz · REFERRAL DETAILS -->
  monday_mirror.cv_status_id(i.column_values, 'color_mm1wrrqz') AS referral_details_id, -- color_mm1wrrqz · REFERRAL DETAILS --> (label id)
  monday_mirror.cv_text(i.column_values, 'color_mm1wm4n4') AS referral_type, -- color_mm1wm4n4 · Referral Type
  monday_mirror.cv_status_id(i.column_values, 'color_mm1wm4n4') AS referral_type_id, -- color_mm1wm4n4 · Referral Type (label id)
  monday_mirror.cv_text(i.column_values, 'color_mm1w5wxr') AS referral_source, -- color_mm1w5wxr · Referral Source
  monday_mirror.cv_status_id(i.column_values, 'color_mm1w5wxr') AS referral_source_id, -- color_mm1w5wxr · Referral Source (label id)
  monday_mirror.cv_text(i.column_values, 'color_mm7d71vd') AS referral_subclass, -- color_mm7d71vd · Referral Subclass
  monday_mirror.cv_status_id(i.column_values, 'color_mm7d71vd') AS referral_subclass_id, -- color_mm7d71vd · Referral Subclass (label id)
  monday_mirror.cv_text(i.column_values, 'color_mm7f2erf') AS referral_region, -- color_mm7f2erf · Referral Region
  monday_mirror.cv_status_id(i.column_values, 'color_mm7f2erf') AS referral_region_id, -- color_mm7f2erf · Referral Region (label id)
  monday_mirror.cv_text(i.column_values, 'color_mm1wjjtk') AS pump_type, -- color_mm1wjjtk · Pump Type
  monday_mirror.cv_status_id(i.column_values, 'color_mm1wjjtk') AS pump_type_id, -- color_mm1wjjtk · Pump Type (label id)
  monday_mirror.cv_text(i.column_values, 'color_mm1w7pmf') AS cgm_type, -- color_mm1w7pmf · CGM Type
  monday_mirror.cv_status_id(i.column_values, 'color_mm1w7pmf') AS cgm_type_id, -- color_mm1w7pmf · CGM Type (label id)
  monday_mirror.cv_text(i.column_values, 'color_mm1w1978') AS request_type, -- color_mm1w1978 · Request Type
  monday_mirror.cv_status_id(i.column_values, 'color_mm1w1978') AS request_type_id, -- color_mm1w1978 · Request Type (label id)
  monday_mirror.cv_text(i.column_values, 'color_mm1yets8') AS cgm_cross_sell, -- color_mm1yets8 · CGM Cross-Sell
  monday_mirror.cv_status_id(i.column_values, 'color_mm1yets8') AS cgm_cross_sell_id, -- color_mm1yets8 · CGM Cross-Sell (label id)
  monday_mirror.cv_text(i.column_values, 'color_mm1w1cm9') AS serving, -- color_mm1w1cm9 · Serving
  monday_mirror.cv_status_id(i.column_values, 'color_mm1w1cm9') AS serving_id, -- color_mm1w1cm9 · Serving (label id)
  monday_mirror.cv_text(i.column_values, 'color_mm1yx6mq') AS email_referral_info, -- color_mm1yx6mq · EMAIL REFERRAL INFO -->
  monday_mirror.cv_status_id(i.column_values, 'color_mm1yx6mq') AS email_referral_info_id, -- color_mm1yx6mq · EMAIL REFERRAL INFO --> (label id)
  monday_mirror.cv_date(i.column_values, 'date_mm1y43ak') AS oow_date, -- date_mm1y43ak · OOW Date
  monday_mirror.cv_time(i.column_values, 'date_mm1y43ak') AS oow_date_time, -- date_mm1y43ak · OOW Date (time of day, ET)
  monday_mirror.cv_text(i.column_values, 'text_mm1yhgf7') AS malfunction_reason, -- text_mm1yhgf7 · Malfunction Reason (text)
  monday_mirror.cv_text(i.column_values, 'dropdown_mm1ygncg') AS current_diabetes_therapy, -- dropdown_mm1ygncg · Current Diabetes Therapy
  monday_mirror.cv_dropdown_ids(i.column_values, 'dropdown_mm1ygncg') AS current_diabetes_therapy_ids, -- dropdown_mm1ygncg · Current Diabetes Therapy (label ids)
  monday_mirror.cv_text(i.column_values, 'color_mm1yd4v5') AS medical_necessity_details, -- color_mm1yd4v5 · MEDICAL NECESSITY DETAILS -->
  monday_mirror.cv_status_id(i.column_values, 'color_mm1yd4v5') AS medical_necessity_details_id, -- color_mm1yd4v5 · MEDICAL NECESSITY DETAILS --> (label id)
  monday_mirror.cv_text(i.column_values, 'color_mm1w5xn1') AS insulin_pump_coverage_path, -- color_mm1w5xn1 · Insulin Pump Coverage Path
  monday_mirror.cv_status_id(i.column_values, 'color_mm1w5xn1') AS insulin_pump_coverage_path_id, -- color_mm1w5xn1 · Insulin Pump Coverage Path (label id)
  monday_mirror.cv_text(i.column_values, 'color_mm1w7e5q') AS cgm_coverage_path, -- color_mm1w7e5q · CGM Coverage Path
  monday_mirror.cv_status_id(i.column_values, 'color_mm1w7e5q') AS cgm_coverage_path_id, -- color_mm1w7e5q · CGM Coverage Path (label id)
  monday_mirror.cv_files(i.column_values, 'file_mm1w5vwp') AS clinical_files, -- file_mm1w5vwp · Clinical Files
  monday_mirror.cv_text(i.column_values, 'color_mm1y4gyp') AS demographics, -- color_mm1y4gyp · DEMOGRAPHICS -->
  monday_mirror.cv_status_id(i.column_values, 'color_mm1y4gyp') AS demographics_id, -- color_mm1y4gyp · DEMOGRAPHICS --> (label id)
  monday_mirror.cv_text(i.column_values, 'text_mm1xvxst') AS dob, -- text_mm1xvxst · DOB (text)
  monday_mirror.cv_phone(i.column_values, 'phone_mm1x44yk') AS pt_phone, -- phone_mm1x44yk · Pt. Phone
  monday_mirror.cv_address(i.column_values, 'location_mm1xhw17') AS patient_address, -- location_mm1xhw17 · Address
  monday_mirror.cv_lat(i.column_values, 'location_mm1xhw17') AS patient_address_lat, -- location_mm1xhw17 · Address (lat)
  monday_mirror.cv_lng(i.column_values, 'location_mm1xhw17') AS patient_address_lng, -- location_mm1xhw17 · Address (lng)
  monday_mirror.cv_text(i.column_values, 'text_mm1xc140') AS email, -- text_mm1xc140 · Email (text)
  monday_mirror.cv_text(i.column_values, 'color_mm1x1bdg') AS gender, -- color_mm1x1bdg · Gender
  monday_mirror.cv_status_id(i.column_values, 'color_mm1x1bdg') AS gender_id, -- color_mm1x1bdg · Gender (label id)
  monday_mirror.cv_text(i.column_values, 'color_mm1x3d9q') AS insurance, -- color_mm1x3d9q · INSURANCE -->
  monday_mirror.cv_status_id(i.column_values, 'color_mm1x3d9q') AS insurance_id, -- color_mm1x3d9q · INSURANCE --> (label id)
  monday_mirror.cv_text(i.column_values, 'color_mm1xycqc') AS active_not_active, -- color_mm1xycqc · Active/Not-Active
  monday_mirror.cv_status_id(i.column_values, 'color_mm1xycqc') AS active_not_active_id, -- color_mm1xycqc · Active/Not-Active (label id)
  monday_mirror.cv_number(i.column_values, 'numeric_mm1zzyph') AS working_coinsurance, -- numeric_mm1zzyph · Co-insurance %
  monday_mirror.cv_text(i.column_values, 'text_mm1xyp9y') AS secondary_insurance_2, -- text_mm1xyp9y · Secondary Insurance (text)
  monday_mirror.cv_number(i.column_values, 'numeric_mm1ztdz4') AS working_deductible, -- numeric_mm1ztdz4 · Deductible
  monday_mirror.cv_number(i.column_values, 'numeric_mm1zv64b') AS working_deductible_remaining, -- numeric_mm1zv64b · Deductible Remaining
  monday_mirror.cv_number(i.column_values, 'numeric_mm1zfv02') AS working_oop_max, -- numeric_mm1zfv02 · OOP Max
  monday_mirror.cv_number(i.column_values, 'numeric_mm1zxktp') AS working_oop_max_remaining, -- numeric_mm1zxktp · OOP Max Remaining
  monday_mirror.cv_text(i.column_values, 'color_mm2bgjxp') AS cgm_pump_insurance, -- color_mm2bgjxp · CGM & Pump Insurance
  monday_mirror.cv_status_id(i.column_values, 'color_mm2bgjxp') AS cgm_pump_insurance_id, -- color_mm2bgjxp · CGM & Pump Insurance (label id)
  monday_mirror.cv_text(i.column_values, 'text_mm2b5bf5') AS cgm_pump_member_id, -- text_mm2b5bf5 · CGM & Pump Member ID (text)
  monday_mirror.cv_text(i.column_values, 'color_mm2bg0rs') AS cgm_pump_ins_active, -- color_mm2bg0rs · CGM & Pump Ins Active?
  monday_mirror.cv_status_id(i.column_values, 'color_mm2bg0rs') AS cgm_pump_ins_active_id, -- color_mm2bg0rs · CGM & Pump Ins Active? (label id)
  monday_mirror.cv_text(i.column_values, 'color_mm2b5e6a') AS supplies_insurance, -- color_mm2b5e6a · Supplies Insurance
  monday_mirror.cv_status_id(i.column_values, 'color_mm2b5e6a') AS supplies_insurance_id, -- color_mm2b5e6a · Supplies Insurance (label id)
  monday_mirror.cv_text(i.column_values, 'text_mm2bs9y4') AS supplies_member_id, -- text_mm2bs9y4 · Supplies Member ID (text)
  monday_mirror.cv_text(i.column_values, 'color_mm2bvmw7') AS supplies_ins_active, -- color_mm2bvmw7 · Supplies Ins Active?
  monday_mirror.cv_status_id(i.column_values, 'color_mm2bvmw7') AS supplies_ins_active_id, -- color_mm2bvmw7 · Supplies Ins Active? (label id)
  monday_mirror.cv_text(i.column_values, 'color_mm2bpw7z') AS monitor_auth_req, -- color_mm2bpw7z · Monitor Auth Req?
  monday_mirror.cv_status_id(i.column_values, 'color_mm2bpw7z') AS monitor_auth_req_id, -- color_mm2bpw7z · Monitor Auth Req? (label id)
  monday_mirror.cv_text(i.column_values, 'color_mm2bekxa') AS monitor_network_status, -- color_mm2bekxa · Monitor Network Status
  monday_mirror.cv_status_id(i.column_values, 'color_mm2bekxa') AS monitor_network_status_id, -- color_mm2bekxa · Monitor Network Status (label id)
  monday_mirror.cv_number(i.column_values, 'numeric_mm2bffek') AS monitor_co_insurance, -- numeric_mm2bffek · Monitor Co-insurance %
  monday_mirror.cv_text(i.column_values, 'color_mm2b1zgq') AS monitor_hcpc, -- color_mm2b1zgq · Monitor HCPC
  monday_mirror.cv_status_id(i.column_values, 'color_mm2b1zgq') AS monitor_hcpc_id, -- color_mm2b1zgq · Monitor HCPC (label id)
  monday_mirror.cv_text(i.column_values, 'color_mm2bscj') AS sensors_auth_req, -- color_mm2bscj · Sensors Auth Req?
  monday_mirror.cv_status_id(i.column_values, 'color_mm2bscj') AS sensors_auth_req_id, -- color_mm2bscj · Sensors Auth Req? (label id)
  monday_mirror.cv_text(i.column_values, 'color_mm2brh0x') AS sensors_network_status, -- color_mm2brh0x · Sensors Network Status
  monday_mirror.cv_status_id(i.column_values, 'color_mm2brh0x') AS sensors_network_status_id, -- color_mm2brh0x · Sensors Network Status (label id)
  monday_mirror.cv_number(i.column_values, 'numeric_mm2byn1k') AS sensors_co_insurance, -- numeric_mm2byn1k · Sensors Co-insurance %
  monday_mirror.cv_text(i.column_values, 'color_mm2b6t98') AS sensors_hcpc, -- color_mm2b6t98 · Sensors HCPC
  monday_mirror.cv_status_id(i.column_values, 'color_mm2b6t98') AS sensors_hcpc_id, -- color_mm2b6t98 · Sensors HCPC (label id)
  monday_mirror.cv_text(i.column_values, 'color_mm2bx2ys') AS insulin_pump_auth_req, -- color_mm2bx2ys · Insulin Pump Auth Req?
  monday_mirror.cv_status_id(i.column_values, 'color_mm2bx2ys') AS insulin_pump_auth_req_id, -- color_mm2bx2ys · Insulin Pump Auth Req? (label id)
  monday_mirror.cv_text(i.column_values, 'color_mm2b91nc') AS insulin_pump_network_status, -- color_mm2b91nc · Insulin Pump Network Status
  monday_mirror.cv_status_id(i.column_values, 'color_mm2b91nc') AS insulin_pump_network_status_id, -- color_mm2b91nc · Insulin Pump Network Status (label id)
  monday_mirror.cv_number(i.column_values, 'numeric_mm2b4nzx') AS insulin_pump_co_insurance, -- numeric_mm2b4nzx · Insulin Pump Co-insurance %
  monday_mirror.cv_text(i.column_values, 'color_mm2bjwvx') AS insulin_pump_hcpc, -- color_mm2bjwvx · Insulin Pump HCPC
  monday_mirror.cv_status_id(i.column_values, 'color_mm2bjwvx') AS insulin_pump_hcpc_id, -- color_mm2bjwvx · Insulin Pump HCPC (label id)
  monday_mirror.cv_text(i.column_values, 'color_mm2btvq0') AS infusion_set_auth_req, -- color_mm2btvq0 · Infusion Set Auth Req?
  monday_mirror.cv_status_id(i.column_values, 'color_mm2btvq0') AS infusion_set_auth_req_id, -- color_mm2btvq0 · Infusion Set Auth Req? (label id)
  monday_mirror.cv_text(i.column_values, 'color_mm2b1ver') AS infusion_set_network_status, -- color_mm2b1ver · Infusion Set Network Status
  monday_mirror.cv_status_id(i.column_values, 'color_mm2b1ver') AS infusion_set_network_status_id, -- color_mm2b1ver · Infusion Set Network Status (label id)
  monday_mirror.cv_number(i.column_values, 'numeric_mm2bksj8') AS infusion_set_co_insurance, -- numeric_mm2bksj8 · Infusion Set Co-insurance %
  monday_mirror.cv_text(i.column_values, 'color_mm2bpvvy') AS infusion_set_hcpc, -- color_mm2bpvvy · Infusion Set HCPC
  monday_mirror.cv_status_id(i.column_values, 'color_mm2bpvvy') AS infusion_set_hcpc_id, -- color_mm2bpvvy · Infusion Set HCPC (label id)
  monday_mirror.cv_text(i.column_values, 'color_mm2bd0q0') AS cartridge_auth_req, -- color_mm2bd0q0 · Cartridge Auth Req?
  monday_mirror.cv_status_id(i.column_values, 'color_mm2bd0q0') AS cartridge_auth_req_id, -- color_mm2bd0q0 · Cartridge Auth Req? (label id)
  monday_mirror.cv_text(i.column_values, 'color_mm2bm7g8') AS cartridge_network_status, -- color_mm2bm7g8 · Cartridge Network Status
  monday_mirror.cv_status_id(i.column_values, 'color_mm2bm7g8') AS cartridge_network_status_id, -- color_mm2bm7g8 · Cartridge Network Status (label id)
  monday_mirror.cv_number(i.column_values, 'numeric_mm2bhdrr') AS cartridge_co_insurance, -- numeric_mm2bhdrr · Cartridge Co-insurance %
  monday_mirror.cv_text(i.column_values, 'color_mm2bxxz2') AS cartridge_hcpc, -- color_mm2bxxz2 · Cartridge HCPC
  monday_mirror.cv_status_id(i.column_values, 'color_mm2bxxz2') AS cartridge_hcpc_id, -- color_mm2bxxz2 · Cartridge HCPC (label id)
  monday_mirror.cv_text(i.column_values, 'color_mm1ycys3') AS doctor, -- color_mm1ycys3 · DOCTOR -->
  monday_mirror.cv_status_id(i.column_values, 'color_mm1ycys3') AS doctor_id, -- color_mm1ycys3 · DOCTOR --> (label id)
  monday_mirror.cv_text(i.column_values, 'color_mm1ychz8') AS doctor_status, -- color_mm1ychz8 · Doctor Status
  monday_mirror.cv_status_id(i.column_values, 'color_mm1ychz8') AS doctor_status_id, -- color_mm1ychz8 · Doctor Status (label id)
  monday_mirror.cv_text(i.column_values, 'text_mm1x46et') AS doctor_name, -- text_mm1x46et · Doctor Name (text)
  monday_mirror.cv_phone(i.column_values, 'phone_mm1xz8c0') AS doctor_phone, -- phone_mm1xz8c0 · Doctor Phone
  monday_mirror.cv_text(i.column_values, 'text_mm1x7d91') AS doctor_npi, -- text_mm1x7d91 · Doctor NPI (text)
  monday_mirror.cv_text(i.column_values, 'color_mm1xw7y5') AS clinicals_method, -- color_mm1xw7y5 · Clinicals Method
  monday_mirror.cv_status_id(i.column_values, 'color_mm1xw7y5') AS clinicals_method_id, -- color_mm1xw7y5 · Clinicals Method (label id)
  monday_mirror.cv_email(i.column_values, 'email_mm1x6fq5') AS doctor_email, -- email_mm1x6fq5 · Doctor Email
  monday_mirror.cv_email(i.column_values, 'email_mm1xdzcj') AS doctor_fax, -- email_mm1xdzcj · Doctor Fax (@rcfax)
  monday_mirror.cv_text(i.column_values, 'dropdown_mm1xbvas') AS clinic_name, -- dropdown_mm1xbvas · Clinic Name
  monday_mirror.cv_dropdown_ids(i.column_values, 'dropdown_mm1xbvas') AS clinic_name_ids, -- dropdown_mm1xbvas · Clinic Name (label ids)
  monday_mirror.cv_address(i.column_values, 'location_mm1xjnfv') AS clinic_address, -- location_mm1xjnfv · Clinic Address
  monday_mirror.cv_lat(i.column_values, 'location_mm1xjnfv') AS clinic_address_lat, -- location_mm1xjnfv · Clinic Address (lat)
  monday_mirror.cv_lng(i.column_values, 'location_mm1xjnfv') AS clinic_address_lng, -- location_mm1xjnfv · Clinic Address (lng)
  monday_mirror.cv_text(i.column_values, 'color_mm1yf9k9') AS stedi, -- color_mm1yf9k9 · STEDI -->
  monday_mirror.cv_status_id(i.column_values, 'color_mm1yf9k9') AS stedi_id, -- color_mm1yf9k9 · STEDI --> (label id)
  monday_mirror.cv_text(i.column_values, 'text_mm1xpgy2') AS stedi_eligibility_active, -- text_mm1xpgy2 · Stedi Eligibility Active? (text)
  monday_mirror.cv_text(i.column_values, 'text_mm25pxed') AS stedi_coverage_type, -- text_mm25pxed · Stedi Coverage Type (text)
  monday_mirror.cv_text(i.column_values, 'text_mm25wrxw') AS stedi_payer_name, -- text_mm25wrxw · Stedi Payer Name (text)
  monday_mirror.cv_text(i.column_values, 'dropdown_mm594743') AS stedi_primary_payer, -- dropdown_mm594743 · Stedi Primary Payer
  monday_mirror.cv_dropdown_ids(i.column_values, 'dropdown_mm594743') AS stedi_primary_payer_ids, -- dropdown_mm594743 · Stedi Primary Payer (label ids)
  monday_mirror.cv_text(i.column_values, 'text_mm25j9aj') AS stedi_medicare_advantage, -- text_mm25j9aj · Stedi Medicare Advantage? (text)
  monday_mirror.cv_text(i.column_values, 'text_mm25pyfx') AS stedi_medicare_advantage_carrier, -- text_mm25pyfx · Stedi Medicare Advantage Carrier (text)
  monday_mirror.cv_text(i.column_values, 'text_mm25j9j7') AS stedi_medicare_advantage_member_id, -- text_mm25j9j7 · Stedi Medicare Advantage Member ID (text)
  monday_mirror.cv_text(i.column_values, 'text_mm25zsdd') AS stedi_qmb, -- text_mm25zsdd · Stedi QMB? (text)
  monday_mirror.cv_text(i.column_values, 'text_mm298skc') AS stedi_medicare_jurisdiction, -- text_mm298skc · Stedi Medicare Jurisdiction (text)
  monday_mirror.cv_text(i.column_values, 'text_mm29kccv') AS stedi_medicaid_mltc, -- text_mm29kccv · Stedi Medicaid MLTC (text)
  monday_mirror.cv_text(i.column_values, 'text_mm2vyta1') AS stedi_managed_medicaid, -- text_mm2vyta1 · Stedi Managed Medicaid (text)
  monday_mirror.cv_text(i.column_values, 'text_mm31e5se') AS stedi_medicaid_id, -- text_mm31e5se · Stedi Medicaid ID (text)
  monday_mirror.cv_text(i.column_values, 'text_mm1xehx8') AS stedi_in_network, -- text_mm1xehx8 · Stedi In Network? (text)
  monday_mirror.cv_text(i.column_values, 'text_mm1xhymg') AS stedi_prior_auth_required, -- text_mm1xhymg · Stedi Prior Auth Required? (text)
  monday_mirror.cv_text(i.column_values, 'text_mm1xssyw') AS stedi_coinsurance, -- text_mm1xssyw · Stedi Coinsurance % (text)
  monday_mirror.cv_text(i.column_values, 'text_mm1xzqe0') AS stedi_copay, -- text_mm1xzqe0 · Stedi Copay (text)
  monday_mirror.cv_text(i.column_values, 'text_mm1x46kd') AS stedi_individual_deductible, -- text_mm1x46kd · Stedi Individual Deductible (text)
  monday_mirror.cv_text(i.column_values, 'text_mm1xyga2') AS stedi_individual_deductible_remaining, -- text_mm1xyga2 · Stedi Individual Deductible Remaining (text)
  monday_mirror.cv_text(i.column_values, 'text_mm1x7hkk') AS stedi_family_deductible, -- text_mm1x7hkk · Stedi Family Deductible (text)
  monday_mirror.cv_text(i.column_values, 'text_mm1xyzqx') AS stedi_family_deductible_remaining, -- text_mm1xyzqx · Stedi Family Deductible Remaining (text)
  monday_mirror.cv_text(i.column_values, 'text_mm1xdtxq') AS stedi_individual_oop_max, -- text_mm1xdtxq · Stedi Individual OOP Max (text)
  monday_mirror.cv_text(i.column_values, 'text_mm1x32jw') AS stedi_individual_oop_max_remaining, -- text_mm1x32jw · Stedi Individual OOP Max Remaining (text)
  monday_mirror.cv_text(i.column_values, 'text_mm1xqmg9') AS stedi_family_oop_max, -- text_mm1xqmg9 · Stedi Family OOP Max (text)
  monday_mirror.cv_text(i.column_values, 'text_mm1xkdgq') AS stedi_family_oop_max_remaining, -- text_mm1xkdgq · Stedi Family OOP Max Remaining (text)
  monday_mirror.cv_text(i.column_values, 'text_mm4tvsk6') AS oop_first, -- text_mm4tvsk6 · OOP Estimate - First (text)
  monday_mirror.cv_text(i.column_values, 'text_mm4ttaa6') AS oop_recurring, -- text_mm4ttaa6 · OOP Estimate - Recurring (text)
  monday_mirror.cv_text(i.column_values, 'text_mm1xsa9') AS stedi_plan_begin_date, -- text_mm1xsa9 · Stedi Plan Begin Date (text)
  monday_mirror.cv_text(i.column_values, 'dropdown_mm30thnj') AS stedi_gender, -- dropdown_mm30thnj · Stedi Gender
  monday_mirror.cv_dropdown_ids(i.column_values, 'dropdown_mm30thnj') AS stedi_gender_ids, -- dropdown_mm30thnj · Stedi Gender (label ids)
  monday_mirror.cv_text(i.column_values, 'text_mm5fqm4s') AS stedi_address, -- text_mm5fqm4s · Stedi Address (text)
  monday_mirror.cv_text(i.column_values, 'text_mm1x9tje') AS stedi_error_description, -- text_mm1x9tje · Stedi Eligibility Error Description (text)
  monday_mirror.cv_text(i.column_values, 'text_mm2nfwjs') AS josh_debug, -- text_mm2nfwjs · Josh Error Log (text)
  monday_mirror.cv_text(i.column_values, 'text_mm2vf40t') AS stuck_reason, -- text_mm2vf40t · stuck reason (text)
  monday_mirror.cv_text(i.column_values, 'direct_doc_mm2trjyb') AS monday_doc_v2, -- direct_doc_mm2trjyb · monday Doc v2 (direct_doc)
  monday_mirror.cv_text(i.column_values, 'color_mm2xe7r8') AS already_in_system, -- color_mm2xe7r8 · Already In System
  monday_mirror.cv_status_id(i.column_values, 'color_mm2xe7r8') AS already_in_system_id, -- color_mm2xe7r8 · Already In System (label id)
  monday_mirror.cv_text(i.column_values, 'text_mm389fs') AS notes, -- text_mm389fs · Profile Send Off Notes (text)
  monday_mirror.cv_text(i.column_values, 'color_mm3822qq') AS follow_up, -- color_mm3822qq · Follow Up
  monday_mirror.cv_status_id(i.column_values, 'color_mm3822qq') AS follow_up_id, -- color_mm3822qq · Follow Up (label id)
  monday_mirror.cv_date(i.column_values, 'date_mm3874an') AS follow_up_date, -- date_mm3874an · Follow Up Date
  monday_mirror.cv_time(i.column_values, 'date_mm3874an') AS follow_up_date_time, -- date_mm3874an · Follow Up Date (time of day, ET)
  monday_mirror.cv_text(i.column_values, 'text_mm3y53qn') AS prescriber_requirements, -- text_mm3y53qn · Prescriber Requirements (text)
  monday_mirror.cv_date(i.column_values, 'date_mm4wh83f') AS plan_begin_date, -- date_mm4wh83f · Plan Begin Date
  monday_mirror.cv_time(i.column_values, 'date_mm4wh83f') AS plan_begin_date_time, -- date_mm4wh83f · Plan Begin Date (time of day, ET)
  monday_mirror.cv_text(i.column_values, 'color_mm52kc3n') AS referral, -- color_mm52kc3n · Referral?
  monday_mirror.cv_status_id(i.column_values, 'color_mm52kc3n') AS referral_id, -- color_mm52kc3n · Referral? (label id)
  monday_mirror.cv_text(i.column_values, 'dropdown_mm5ex3d7') AS stedi_facility_flags, -- dropdown_mm5ex3d7 · SNF/Hospice/Hospital
  monday_mirror.cv_dropdown_ids(i.column_values, 'dropdown_mm5ex3d7') AS stedi_facility_flags_ids, -- dropdown_mm5ex3d7 · SNF/Hospice/Hospital (label ids)
  monday_mirror.cv_text(i.column_values, 'color_mm5zb8h6') AS form_reason_for_inquiry, -- color_mm5zb8h6 · Reason for Inquiry
  monday_mirror.cv_status_id(i.column_values, 'color_mm5zb8h6') AS form_reason_for_inquiry_id, -- color_mm5zb8h6 · Reason for Inquiry (label id)
  monday_mirror.cv_text(i.column_values, 'text_mm5zc4vy') AS form_state, -- text_mm5zc4vy · State (text)
  monday_mirror.cv_text(i.column_values, 'color_mm5zsfmj') AS form_pump_need, -- color_mm5zsfmj · Pump Need
  monday_mirror.cv_status_id(i.column_values, 'color_mm5zsfmj') AS form_pump_need_id, -- color_mm5zsfmj · Pump Need (label id)
  monday_mirror.cv_text(i.column_values, 'color_mm5z5v3n') AS form_cgm_preference, -- color_mm5z5v3n · Provided CGM Preference
  monday_mirror.cv_status_id(i.column_values, 'color_mm5z5v3n') AS form_cgm_preference_id, -- color_mm5z5v3n · Provided CGM Preference (label id)
  monday_mirror.cv_text(i.column_values, 'color_mm5zxfh9') AS form_pump_preference, -- color_mm5zxfh9 · Provided Pump Preference
  monday_mirror.cv_status_id(i.column_values, 'color_mm5zxfh9') AS form_pump_preference_id, -- color_mm5zxfh9 · Provided Pump Preference (label id)
  monday_mirror.cv_text(i.column_values, 'text_mm5z586h') AS form_provided_doctor_name, -- text_mm5z586h · Provided Doctor Name (text)
  monday_mirror.cv_text(i.column_values, 'text_mm5zjh88') AS form_provided_clinic_phone, -- text_mm5zjh88 · Provided Clinic Phone (text)
  monday_mirror.cv_text(i.column_values, 'color_mm5zv5pa') AS form_insurance_via, -- color_mm5zv5pa · Insurance Provided Via
  monday_mirror.cv_status_id(i.column_values, 'color_mm5zv5pa') AS form_insurance_via_id, -- color_mm5zv5pa · Insurance Provided Via (label id)
  monday_mirror.cv_text(i.column_values, 'text_mm5z8w99') AS form_insurance_other, -- text_mm5z8w99 · Insurance (Other) - as typed (text)
  monday_mirror.cv_text(i.column_values, 'color_mm5zh2af') AS form_secondary_provided, -- color_mm5zh2af · Secondary Insurance (as provided)
  monday_mirror.cv_status_id(i.column_values, 'color_mm5zh2af') AS form_secondary_provided_id, -- color_mm5zh2af · Secondary Insurance (as provided) (label id)
  monday_mirror.cv_text(i.column_values, 'text_mm5ztdq9') AS form_secondary_member_id, -- text_mm5ztdq9 · Secondary Member ID (as provided) (text)
  monday_mirror.cv_files(i.column_values, 'file_mm5zhy1') AS form_card_photo, -- file_mm5zhy1 · Insurance Card Photo
  monday_mirror.cv_text(i.column_values, 'color_mm5zp6rt') AS form_proceed_preference, -- color_mm5zp6rt · Proceed Preference
  monday_mirror.cv_status_id(i.column_values, 'color_mm5zp6rt') AS form_proceed_preference_id, -- color_mm5zp6rt · Proceed Preference (label id)
  monday_mirror.cv_text(i.column_values, 'text_mm5za6zx') AS form_call_slot, -- text_mm5za6zx · Call Slot - Selected on Form (text)
  monday_mirror.cv_text(i.column_values, 'color_mm5zrbn3') AS form_booking_status, -- color_mm5zrbn3 · Booking Status
  monday_mirror.cv_status_id(i.column_values, 'color_mm5zrbn3') AS form_booking_status_id, -- color_mm5zrbn3 · Booking Status (label id)
  monday_mirror.cv_text(i.column_values, 'color_mm5zv7q8') AS form_drop_off_step, -- color_mm5zv7q8 · Drop-off Step
  monday_mirror.cv_status_id(i.column_values, 'color_mm5zv7q8') AS form_drop_off_step_id, -- color_mm5zv7q8 · Drop-off Step (label id)
  monday_mirror.cv_text(i.column_values, 'text_mm5zmfgg') AS form_session_id, -- text_mm5zmfgg · Form Session ID (text)
  monday_mirror.cv_text(i.column_values, 'color_mm5z31hs') AS self_advocacy, -- color_mm5z31hs · Self Advocacy
  monday_mirror.cv_status_id(i.column_values, 'color_mm5z31hs') AS self_advocacy_id, -- color_mm5z31hs · Self Advocacy (label id)
  monday_mirror.cv_text(i.column_values, 'text_mm5zj2q1') AS current_oop_cost, -- text_mm5zj2q1 · Current Out-of-Pocket Cost (text)
  monday_mirror.cv_text(i.column_values, 'color_mm5z4yqq') AS cgm_data_awareness, -- color_mm5z4yqq · CGM Data & Doctor Awareness
  monday_mirror.cv_status_id(i.column_values, 'color_mm5z4yqq') AS cgm_data_awareness_id, -- color_mm5z4yqq · CGM Data & Doctor Awareness (label id)
  monday_mirror.cv_files(i.column_values, 'file_mm5zhsxh') AS cgm_data_file, -- file_mm5zhsxh · CGM Data File
  monday_mirror.cv_number(i.column_values, 'numeric_mm5ze82q') AS attempt_counter, -- numeric_mm5ze82q · Attempt Counter
  monday_mirror.cv_text(i.column_values, 'color_mm5z6eze') AS intake_call_complete, -- color_mm5z6eze · Intake Call Complete
  monday_mirror.cv_status_id(i.column_values, 'color_mm5z6eze') AS intake_call_complete_id, -- color_mm5z6eze · Intake Call Complete (label id)
  monday_mirror.cv_text(i.column_values, 'color_mm5zww42') AS intake_escalation, -- color_mm5zww42 · Intake Escalation
  monday_mirror.cv_status_id(i.column_values, 'color_mm5zww42') AS intake_escalation_id, -- color_mm5zww42 · Intake Escalation (label id)
  monday_mirror.cv_text(i.column_values, 'long_text_mm5z3sq9') AS intake_escalation_notes, -- long_text_mm5z3sq9 · Intake Escalation Notes (long_text)
  monday_mirror.cv_text(i.column_values, 'color_mm5zhw4e') AS rx_docs_to_patient, -- color_mm5zhw4e · Rx Docs to Patient
  monday_mirror.cv_status_id(i.column_values, 'color_mm5zhw4e') AS rx_docs_to_patient_id, -- color_mm5zhw4e · Rx Docs to Patient (label id)
  monday_mirror.cv_text(i.column_values, 'text_mm5zqtz1') AS rx_docs_detail, -- text_mm5zqtz1 · Rx Docs Detail (text)
  monday_mirror.cv_date(i.column_values, 'date_mm63na19') AS scheduled_call_time, -- date_mm63na19 · Scheduled Call Time
  monday_mirror.cv_time(i.column_values, 'date_mm63na19') AS scheduled_call_time_time, -- date_mm63na19 · Scheduled Call Time (time of day, ET)
  monday_mirror.cv_text(i.column_values, 'text_mm63e086') AS calendly_event_uri, -- text_mm63e086 · Calendly Event URI (text)
  monday_mirror.cv_date(i.column_values, 'date_mm647ck0') AS last_form_activity, -- date_mm647ck0 · Last Form Activity
  monday_mirror.cv_time(i.column_values, 'date_mm647ck0') AS last_form_activity_time, -- date_mm647ck0 · Last Form Activity (time of day, ET)
  monday_mirror.cv_date(i.column_values, 'date_mm644d3s') AS drop_off_text_sent, -- date_mm644d3s · Drop-off Text Sent
  monday_mirror.cv_time(i.column_values, 'date_mm644d3s') AS drop_off_text_sent_time, -- date_mm644d3s · Drop-off Text Sent (time of day, ET)
  monday_mirror.cv_text(i.column_values, 'long_text_mm651jfa') AS dup_check_analysis, -- long_text_mm651jfa · Dup Check Analysis (long_text)
  monday_mirror.cv_text(i.column_values, 'text_mm65xbm0') AS matched_patient_uid, -- text_mm65xbm0 · Matched Patient UID (text)
  monday_mirror.cv_text(i.column_values, 'color_mm65tv1m') AS dup_check_result, -- color_mm65tv1m · Dup Check Result
  monday_mirror.cv_status_id(i.column_values, 'color_mm65tv1m') AS dup_check_result_id, -- color_mm65tv1m · Dup Check Result (label id)
  monday_mirror.cv_number(i.column_values, 'numeric_mm67822b') AS drop_off_attempt, -- numeric_mm67822b · Drop-off Attempt
  monday_mirror.cv_text(i.column_values, 'color_mm6ct431') AS intake_sub_stage, -- color_mm6ct431 · Intake Sub-Stage
  monday_mirror.cv_status_id(i.column_values, 'color_mm6ct431') AS intake_sub_stage_id, -- color_mm6ct431 · Intake Sub-Stage (label id)
  monday_mirror.cv_date(i.column_values, 'date_mm6eakae') AS resume_link_sent, -- date_mm6eakae · Resume Link Sent
  monday_mirror.cv_time(i.column_values, 'date_mm6eakae') AS resume_link_sent_time, -- date_mm6eakae · Resume Link Sent (time of day, ET)
  monday_mirror.cv_date(i.column_values, 'date_mm6eev4b') AS insurance_link_sent, -- date_mm6eev4b · Insurance Link Sent
  monday_mirror.cv_time(i.column_values, 'date_mm6eev4b') AS insurance_link_sent_time, -- date_mm6eev4b · Insurance Link Sent (time of day, ET)
  monday_mirror.cv_text(i.column_values, 'long_text_mm7g4b4h') AS intake_warnings, -- long_text_mm7g4b4h · Intake Warnings (long_text)
  monday_mirror.cv_text(i.column_values, 'text_mm7g1hr') AS intake_warning_acks -- text_mm7g1hr · Intake Warning Acks (text)
FROM monday_mirror.items i
LEFT JOIN monday_mirror.groups g ON g.board_id = i.board_id AND g.group_id = i.group_id
WHERE i.board_id = 18406352652;
